//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public Avaliacao()
        {
            this.Usu_Aval_Comp = new HashSet<Usu_Aval_Comp>();
        }
    
        public int aval_id { get; set; }
        public decimal aval_nivel { get; set; }
        public System.DateTime aval_data { get; set; }
        public int aval_usu_id { get; set; }
        public bool aval_atual { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Usu_Aval_Comp> Usu_Aval_Comp { get; set; }
    }
}
