//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.Projeto_Funcionario = new HashSet<Projeto_Funcionario>();
            this.Competencias = new HashSet<Competencia>();
        }
    
        public int proj_id { get; set; }
        public string proj_nome { get; set; }
        public string proj_descricao { get; set; }
        public System.DateTime proj_data_inicio { get; set; }
        public System.DateTime proj_data_termino { get; set; }
        public string proj_status { get; set; }
        public string proj_prioridade { get; set; }
        public int proj_usu_id { get; set; }
        public bool proj_avaliado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Projeto_Funcionario> Projeto_Funcionario { get; set; }
        public virtual ICollection<Competencia> Competencias { get; set; }
    }
}
