//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAARHEntities : DbContext
    {
        public SAARHEntities()
            : base("name=SAARHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avaliacao> Avaliacaos { get; set; }
        public virtual DbSet<Competencia> Competencias { get; set; }
        public virtual DbSet<Projeto> Projetoes { get; set; }
        public virtual DbSet<Projeto_Funcionario> Projeto_Funcionario { get; set; }
        public virtual DbSet<Tipo_Competencia> Tipo_Competencia { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public virtual DbSet<Usu_Aval_Comp> Usu_Aval_Comp { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<SP_GetRecursosHumanos_Result> SP_GetRecursosHumanos(Nullable<int> comp0, Nullable<int> comp1, Nullable<int> comp2, Nullable<int> comp3, Nullable<int> comp4, Nullable<int> comp5, Nullable<int> comp6, Nullable<int> comp7, Nullable<int> comp8, Nullable<int> comp9)
        {
            var comp0Parameter = comp0.HasValue ?
                new ObjectParameter("comp0", comp0) :
                new ObjectParameter("comp0", typeof(int));
    
            var comp1Parameter = comp1.HasValue ?
                new ObjectParameter("comp1", comp1) :
                new ObjectParameter("comp1", typeof(int));
    
            var comp2Parameter = comp2.HasValue ?
                new ObjectParameter("comp2", comp2) :
                new ObjectParameter("comp2", typeof(int));
    
            var comp3Parameter = comp3.HasValue ?
                new ObjectParameter("comp3", comp3) :
                new ObjectParameter("comp3", typeof(int));
    
            var comp4Parameter = comp4.HasValue ?
                new ObjectParameter("comp4", comp4) :
                new ObjectParameter("comp4", typeof(int));
    
            var comp5Parameter = comp5.HasValue ?
                new ObjectParameter("comp5", comp5) :
                new ObjectParameter("comp5", typeof(int));
    
            var comp6Parameter = comp6.HasValue ?
                new ObjectParameter("comp6", comp6) :
                new ObjectParameter("comp6", typeof(int));
    
            var comp7Parameter = comp7.HasValue ?
                new ObjectParameter("comp7", comp7) :
                new ObjectParameter("comp7", typeof(int));
    
            var comp8Parameter = comp8.HasValue ?
                new ObjectParameter("comp8", comp8) :
                new ObjectParameter("comp8", typeof(int));
    
            var comp9Parameter = comp9.HasValue ?
                new ObjectParameter("comp9", comp9) :
                new ObjectParameter("comp9", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRecursosHumanos_Result>("SP_GetRecursosHumanos", comp0Parameter, comp1Parameter, comp2Parameter, comp3Parameter, comp4Parameter, comp5Parameter, comp6Parameter, comp7Parameter, comp8Parameter, comp9Parameter);
        }
    }
}
