//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Usuario
    {
        public Tipo_Usuario()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int tipo_id { get; set; }
        public string tipo_nome { get; set; }
        public string tipo_descricao { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
