//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Competencia
    {
        public Tipo_Competencia()
        {
            this.Competencias = new HashSet<Competencia>();
        }
    
        public int tcom_id { get; set; }
        public string tcom_nome { get; set; }
    
        public virtual ICollection<Competencia> Competencias { get; set; }
    }
}
