//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usu_Aval_Comp
    {
        public int uac_usu_id { get; set; }
        public int uac_aval_id { get; set; }
        public int uac_comp_id { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Competencia Competencia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
