//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Avaliacaos = new HashSet<Avaliacao>();
            this.Projetoes = new HashSet<Projeto>();
            this.Projeto_Funcionario = new HashSet<Projeto_Funcionario>();
            this.Usu_Aval_Comp = new HashSet<Usu_Aval_Comp>();
        }
    
        public int usu_id { get; set; }
        public string usu_nome { get; set; }
        public string usu_sobrenome { get; set; }
        public string usu_nome_usuario { get; set; }
        public string usu_senha { get; set; }
        public int usu_tipo_id { get; set; }
        public string usu_email { get; set; }
        public string usu_salt { get; set; }
    
        public virtual ICollection<Avaliacao> Avaliacaos { get; set; }
        public virtual ICollection<Projeto> Projetoes { get; set; }
        public virtual ICollection<Projeto_Funcionario> Projeto_Funcionario { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
        public virtual ICollection<Usu_Aval_Comp> Usu_Aval_Comp { get; set; }
    }
}
